version: '3.3'
services:
  sqldb:
    image: mysql:8.0
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - sqlstore:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=example123
      - MYSQL_PASSWORD=example123
      - MYSQL_ROOT_HOST:'%'

    

      

  phpmyadmin:
    container_name: phpmyadmin_containers
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: on-failure
    environment:
      PMA_HOST: sqldb
      PMA_USER: root
      PMA_PASSWORD: example123
    ports:
      - '0.0.0.0:8084:80'

  # rabbitmq:
  #   container_name: rabbitmq
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   volumes:
  #     - docker-data:/var/lib/rabbitmq/
  #     - docker-log:/var/log/rabbitmq/

  # redis:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6377:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # volumes: 
    #   - cache:/data
  # ibaxuserbackend:
  #   build:
  #     context: './ibaxuserbackend'
  #     dockerfile: Dockerfile
  #   container_name: ibaxuserbackend
  #   restart: unless-stopped
  #   env_file: ./ibaxuserbackend/.env
  #   ports:
  #     - 4001:4001
  #   depends_on:
  #     - sqldb
  #   volumes:
  #     - ./ibaxuserbackend:/src

    # command: ./wait-for.sh mysql-services:3306 -- /home/node/app/node_modules/.bin/nodemon app.js

volumes:
  sqlstore:
  docker-data:
  docker-log:
  cache: